name: Trigger Jenkins Job from GitHub

on:
  push:
    branches:
      - main  

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      - name: Trigger Jenkins via REST API
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB_NAME/build?token=$JENKINS_TRIGGER_TOKEN" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN"
        env:
          JENKINS_URL: 'http://13.61.0.69:8080'
          JENKINS_USER: 'ankit'
          JENKINS_API_TOKEN: '1172023e2cd1f98152adbf21bb426e94d4'
          JENKINS_JOB_NAME: 'freestyleproject'
          JENKINS_TRIGGER_TOKEN: 'trigger-from-github'

