name: Trigger Jenkins Job from GitHub

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      - name: Trigger Jenkins via REST API
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB_NAME/build?token=$JENKINS_TRIGGER_TOKEN" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN"
        env:
          JENKINS_URL: 'http://13.61.6.50:8080'
          JENKINS_USER: 'ankit'
          JENKINS_API_TOKEN: '11608d3d43b41efb7fb7dfeffeebc0f3b9'
          JENKINS_JOB_NAME: 'freestyleproject'
          JENKINS_TRIGGER_TOKEN: 'trigger-from-github'

